services:
  - type: web
    name: wine-service-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    buildFilter:
      paths:
        - backend/**
    envVars:
      - key: DATABASE_URL
        value: sqlite:///wineservice.db
