build:
  environment:
    pythonVersion: "3.11"

services:
  - type: web
    name: wine-service-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
